### ISSUE TITLE
Dispute Classification

### ISSUE THREAD

**Issue by S3BzA** [COS301-SE-2024/Dispute-Resolution-Engine#184]
[distilbart-mnli-12-1](https://huggingface.co/valhalla/distilbart-mnli-12-1)

**TODO**:
- [ ] Use distilbart to classify disputes
- [x] Add enum for possible classifications
- [ ] Add option to manually classify dispute

**Comment by ghost** [comment]
The dispute type will be determined by the workflow template that it follows, so classification is not needed
