### ISSUE TITLE
Add a description tooltip for workflow states

### ISSUE THREAD

**Issue by ghost** [COS301-SE-2024/Dispute-Resolution-Engine#367]
Because workflows can be dynamic, it would be nice if each state of a dispute had a description that would describe to the user what that state means

**TODO:**
- [x] Tooltip in UI
- [x] Descriptions in JSON schema
- [x] Add user story to documentation
