### ISSUE TITLE
Group disputes by status

### ISSUE THREAD

**Issue by ghost** [COS301-SE-2024/Dispute-Resolution-Engine#376]
It would be nice for a user to be able to separate active disputes from completed disputes. There are two ways to approach this:
1. Accordion view for completed vs. active  (suggested by @ZaguePrime)
2. Two seperate bullet lists

**TODO:**
- [ ] API fields for dispute status
- [ ] UI mockups in penpot
- [ ] Implementation in frontend
- [ ] User stories in documentation
