### ISSUE TITLE
Integrate the admin dispute list with the API

### ISSUE THREAD

**Issue by ghost** [COS301-SE-2024/Dispute-Resolution-Engine#442]
The frontend and services for the admin disputes list is complete. Now they must talk to each other

**TODO**
- [x] Determine the color of the status badge based on the  the enum value

**Comment by ghost** [comment]
Some e2e testing to do (@MichaelHorwitz):
- [ ] Filtering a dispute by status
- [ ] Testing pagination
- [ ] Testing the dispute details are displayed correctly
